server:
  port: 8090
  servlet:
    context-path: /api/yungyangDD
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  jwt:
    secret: youngyangaustin
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  jpa:

    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true



  datasource:
    url: jdbc:mysql://localhost:3306/yungyangDD?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF8&profileSQL=true&serverTimezone=UTC&rewriteBatchedStatements=true&logger=com.mysql.cj.log.Slf4JLogger&allowPublicKeyRetrieval=true
    username: root
    password: austin
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 1
      minimum-idle: 2
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true



app:
  filePath: /var/app/poc_dev/upload
#  filePath: /var/app/poc/upload
#  filePath: /Users/austin/Documents/laonstory/poc_be_spring/upload

