server:
  port: 5190
  servlet:
    context-path: /api/linen_lite
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  jwt:
    secret: spogymlaon
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql : true



  datasource:
    url: jdbc:mariadb://localhost:3306/linen_lite?characterEncoding=UTF-8&ServerTimezone=UTC
    username: root
    password: Laonpp00..L
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true



app:
  filePath: \var\app\lite\upload


